### ISSUE TITLE
Convert `memory.coffee` to JavaScript

### ISSUE THREAD

**Issue by locks** [brandonjmckay/tomster-chatbot#9]
I don't frequently use CoffeeScript, so the syntax/semantics are unfamiliar enough that I have to look up things when working on the script.

This task consists of converting the memory script as directly as possible to JavaScript.

**Comment by tragiclifestories** [comment]
I can take this, although presumably it would be a good idea to convert all of them?

Also: what node version(s) does this have to support? If we can restrict it to 6+, then that will have obvious ES2015 benefits.

**Comment by bj-mcduck** [comment]
@tragiclifestories I would only do our special functions, which is only `/scripts/api-links.coffee`, and `/scripts/memory.coffee`

**Comment by locks** [comment]
Given tomster isn't exactly working at the moment, we can punt on this.
